android.experimental.enableNewResourceShrinker.preciseShrinking=true
android.enableAppCompileTimeRClass=true
android.useAndroidX=true
org.gradle.jvmargs=-Xmx2048m
org.gradle.parallel=true
org.gradle.vfs.watch=true
android.r8.maxWorkers=4

# zsu private fork signing
KEYSTORE_FILE=zsu.keystore
KEYSTORE_PASSWORD=FmYWLwdw3DdJyGiEd5UmFJlQ
KEY_ALIAS=zsu
KEY_PASSWORD=FmYWLwdw3DdJyGiEd5UmFJlQ
